[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_LOOP_STACK_SIZE=12288
    -DLPWA_ENABLE_WIFI_LR=1
    -DLPWA_ENABLE_BLE_RELAY=1
    -DLPWA_ALLOW_WIFI_LR_WITH_BLE=0
    -DLPWA_ENABLE_TRACE_TELEMETRY=0
    -DLPWA_MESH_CHANNEL=1
    -DLPWA_MESH_TX_POWER_QDBM=72
lib_deps =
    bblanchon/ArduinoJson@^6.21.5
    h2zero/NimBLE-Arduino@^2.3.6
